### PR TITLE
update JP translations

### PR DESCRIPTION
**Pull request by calamath**
Japanese language mode support

### CODE REVIEW

**Comment by calamath** [comment]
The following are the results displayed in Japanese mode with the Japanese ESO client software.
The headline width is still 38 and no display loss has occurred.
WIDTH38_jp_mode

By the way, here's the result of displaying in English mode with the Japanese ESO client software.
It seems that Wednesday doesn't display well with the headline width of 38. 
Could it be that the font settings used by the Japanese ESO client software are different?
WIDTH38_en_mode

**Comment by Baertram** [comment]
Hi Calamath, thanks for the test. With my client the Wednesday was clearly visible as "Wed". I'll test it again, maybe it's your screen resolution or scaling?
I'm using 1920x1200 with default scaling.

**Comment by calamath** [comment]
Oops, you're right.
I just remembered that I had ESOUI set to 'Windowed mode' to take screenshots.
This was a problem caused by scaling. In fullscreen, it was displayed properly without missing anything.   ;-p

**Comment by Baertram** [comment]
Thanks for the quick answer + tests, aswell as the JP translations. Updating it now

**Pull request merged**
